[package]
name = "parasol_cpu_macros"
version = "0.9.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
proc-macro2 = "1.0.81"
syn = "2.0.60"

[dev-dependencies]
prettyplease = "0.2.19"